<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Documentation Defaults
    |--------------------------------------------------------------------------
    |
    | Define the default route-loader and set all documentation generators
    |
    */
    'defaults' => [
        'loader' => 'laravelRouteLoader',
        'sorter' => 'sortByGroup',
        'generators' => ['MDGenerator', 'PostmanCollectionGenerator'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Route Loaders
    |--------------------------------------------------------------------------
    |
    | Next, you may define every route-loader for your application.
    |
    | Each loader can have additional settings. The whole config-array
    | is injected into the __construct method of the class.
    |
    */
    'loaders' => [
        'laravelRouteLoader' => [
            'loader' => \Nicolaskuster\ApiDoc\Loader\LaravelRouteLoader::class,
            'routeModel' => \Nicolaskuster\ApiDoc\Models\LaravelRoute::class,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Route Sorters
    |--------------------------------------------------------------------------
    |
    | Next, you may define every route-sorter for your application.
    |
    | Each sorter can have additional settings. The whole config-array
    | is injected into the __construct method of the class.
    |
    */
    'sorters' => [
        'sortByGroup' => [
            'sorter' => \Nicolaskuster\ApiDoc\Support\DefaultRouteSorter::class,
            'order' => ['index', 'GET', 'create', 'store', 'POST', 'show', 'edit', 'update', 'PUT', 'PATCH', 'destroy', 'DELETE'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Documentation Generators
    |--------------------------------------------------------------------------
    |
    | Next, you may define generators for your application.
    |
    | Each generator can have additional settings. The whole config-array
    | is injected into the __construct method of the class.
    |
    */
    'generators' => [
        'MDGenerator' => [
            'generator' => \Nicolaskuster\ApiDoc\Generators\MDGenerator::class,
            'outputPath' => base_path('apiDoc.md')
        ],
        'PostmanCollectionGenerator' => [
            'generator' => \Nicolaskuster\ApiDoc\Generators\PostmanCollectionGenerator::class,
            'outputPath' => base_path('apiDoc.postman_collection.json'),
            'outputStyle' => \Nicolaskuster\ApiDoc\Generators\PostmanCollectionGenerator::OUTPUT_STYLE_GROUPED,
            'collection' => [
                'name' => env('APP_NAME'),
                'description' => 'Generated by apiDoc',
                'urlVariableKey' => 'APP_URL',
                'variables' => [
                    'APP_URL' => env('APP_URL'),
                    'API_TOKEN' => 'secret'
                ],
                'headers' => [
                    'Accept' => [
                        'value' => 'application/json',
                        'description' => ''
                    ]
                ],
                'perMiddleware' => [
                    'auth:api' => [
                        'headers' => [
                            'Authorization' => [
                                'value' => 'Bearer {{API_TOKEN}}',
                                'description' => ''
                            ],
                        ]
                    ]
                ]
            ]
        ]
    ]
];
